version: "3.2"  # optional since v1.27.0
services:
    reactivechess:
        build:
            context: .
            args:
                USER_ID: "${USER_ID:-1000}"
                GROUP_ID: "${GROUP_ID:-1000}"
        ports:
            - "8010:8010"
        command: /bin/sh -c "rm -f /opt/app/tmp/pids/server.pid; rails s"
        volumes:
            - ./reactive-chess:/opt/app
            - /opt/app/config
        networks:
            - frontend
            - backend
        env_file:
            - .env

    redis:
        image: redis:5.0.7
        ports:
            - '6379:6379'
        volumes:
            - chess-redis:/var/lib/redis/data
        networks:
            - backend

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: reactivechess
            POSTGRES_PASSWORD: example
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgresVolume1:/var/lib/postgresql/data
        networks:
            - backend

    adminer:
        image: adminer
        ports:
            - 8081:8080
        networks:
            - backend

    sidekiq:
        build:
            context: .
            args:
                USER_ID: "${USER_ID:-1000}"
                GROUP_ID: "${GROUP_ID:-1000}"
        command: bundle exec sidekiq 
        networks:
            - backend
        env_file:
            - .env

    nginx:
        build:
            context: .
            dockerfile: ./Dockerfile.nginx
        networks:
            - frontend
        ports:
            - '8020:8020'
        
volumes:
    postgresVolume1: 
    chess-redis: 

networks:
    frontend: 
    backend:
